### ISSUE TITLE
Crash with Newer Versions

### ISSUE THREAD

**Issue by Blunder-G** [Globox1997/RpgDifficulty#1]
First version of RPGD is okay for me. But newer versions crashes my game upon start.

I searched for the crash report but it didn't generate it. I can send a crash I got earlier. This way you can see the mod list: 
[crash-2021-05-26_22.56.00-server.txt](https://github.com/Globox1997/RpgDifficulty/files/6551517/crash-2021-05-26_22.56.00-server.txt)

**Comment by Globox1997** [comment]
Does this happen with version 1.0.3?

**Comment by Blunder-G** [comment]
Yes

**Comment by Globox1997** [comment]
Without rpg difficulty this doesn't happen? And the crash log says, it happens when loading/generating structures

**Comment by Blunder-G** [comment]
I don't know, but it's just crashs my game when loading

**Comment by Globox1997** [comment]
Please check out the latest version :)

**Comment by Blunder-G** [comment]
I think it's okey with newer versions! But as i said: i think...
