### ISSUE TITLE
[Feature Request] Starting factor

### ISSUE THREAD

**Issue by elhertz** [Globox1997/RpgDifficulty#11]
Example:
- Let's say I want to play on hell mode and start with a 5.0 factor in the overworld (then scaling from that on time/distance).

**Comment by Globox1997** [comment]
Added a starting factor with [https://github.com/Globox1997/RpgDifficulty/commit/9726a80041d50e25f7ce193afd3348276604f943](https://github.com/Globox1997/RpgDifficulty/commit/9726a80041d50e25f7ce193afd3348276604f943)
