### ISSUE TITLE
[Feature Request] Add per world settings

### ISSUE THREAD

**Issue by elhertz** [Globox1997/RpgDifficulty#12]
I think this feature is very important!
Examples:
- Scale the mobs differently in every world (increasingDistance, timeFactor, xpFactor, etc.)
- If you add #11 you could make the nether/end or other custom dimensions a little more difficult, forcing players to really prepare for it as the difficulty is already high.
- If you add #6 it could be a nice feature to start leveling mobs where the end islands start generating (the space in between the main End island and the End islands it's too big but "distanceFactor" doesn't care about that).
- Have a crazy dimension with increased random factor, it'd be fun!

**Comment by Globox1997** [comment]
That is actually a really good idea, just don't know yet how to implement this

**Comment by Globox1997** [comment]
Now added per dimension difficulty with [https://github.com/Globox1997/RpgDifficulty/commit/fe27e475e77c71d8db028b192fd9c53d63c4d4c2](https://github.com/Globox1997/RpgDifficulty/commit/fe27e475e77c71d8db028b192fd9c53d63c4d4c2)
For more info check out the github readme
