### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by ModMan2021** [Globox1997/RpgDifficulty#13]
Option for creeper explosion damage (perhaps explosion radius too)
And also for the increased damaged as an option to not do more durability damage on shields or armor, as shields break extremely fast if you make the damage scale a lot

**Comment by Globox1997** [comment]
Added setting for creepers with [https://github.com/Globox1997/RpgDifficulty/commit/44385f0f2864c4129afbac2de705cac4e16b7b15](https://github.com/Globox1997/RpgDifficulty/commit/44385f0f2864c4129afbac2de705cac4e16b7b15)
Haven't added your second request but in my eyes this is enough
