### ISSUE TITLE
Starting Factor affects all mobs speed with no way to scale

### ISSUE THREAD

**Issue by LunchBox951** [Globox1997/RpgDifficulty#16]
The setting "startingfactor" will change all mobs speed, but will not allow the speed to scale back up, either nerfing or buffing all mobs speed at all distances.

To re-create: set "startingfactor" to 0.5. Spawn a mob and observe the slow speed. travel any distance out and spawn another. They will have the same speed.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/RpgDifficulty/commit/f68cbf0b9547837541314e6876b0e55b3dd2b8a1](https://github.com/Globox1997/RpgDifficulty/commit/f68cbf0b9547837541314e6876b0e55b3dd2b8a1)
