### ISSUE TITLE
issue with the exclude entity list.

### ISSUE THREAD

**Issue by Keebsz** [Globox1997/RpgDifficulty#17]
I noticed an issue with config. On line 46 its
// Exluded Entity List Bsp: minecraft.villager

Exclude is missing a C
I generated a new config file and got the same issue.
I assume this is what made the villagers start having levels near their names.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/RpgDifficulty/commit/a160f8636ca29d73c3356738abc9216760ef55e1](https://github.com/Globox1997/RpgDifficulty/commit/a160f8636ca29d73c3356738abc9216760ef55e1)
It uses now ":" as a separator
