### ISSUE TITLE
[Feature Request] Minimum level mobs per dimension 

### ISSUE THREAD

**Issue by Balakay420** [Globox1997/RpgDifficulty#21]
a way to set a minimum level/difficulty for mobs in a specific world/dimension? Example: mobs in nether are automatically level 50, mobs in the end are automatically level 100. But the difficulty still increases depending on your config.
- https://github.com/Globox1997/RpgDifficulty/issues/12 (I just saw this)

**Comment by Monster-Zer0** [comment]
https://github.com/Globox1997/RpgZ/issues/26

bumping

**Comment by Globox1997** [comment]
Added per dimension difficulty with [https://github.com/Globox1997/RpgDifficulty/commit/fe27e475e77c71d8db028b192fd9c53d63c4d4c2](https://github.com/Globox1997/RpgDifficulty/commit/fe27e475e77c71d8db028b192fd9c53d63c4d4c2)
Check out the readme for more info
