### ISSUE TITLE
[Crash] Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by lindenkron** [Globox1997/RpgDifficulty#25]
Unsure if it's RPGDifficulty, but I seem unable to crash the server after removing it.

I also had another type of crash that I attributed to Graveyard mod that seems to be opened in #24 . I didn't know that crash was related to having both mods installed, so that's nice to know.

This crash however was without Graveyard added.

Two logs. Identical errors. Only one mentions RPGDifficulties though:
[crash-2022-06-21_01.09.47-server.txt](https://github.com/Globox1997/RpgDifficulty/files/8953111/crash-2022-06-21_01.09.47-server.txt)
[crash-2022-06-21_01.15.51-server.txt](https://github.com/Globox1997/RpgDifficulty/files/8953112/crash-2022-06-21_01.15.51-server.txt)

Hope it helps, posted as requested from CF :)

**Comment by Globox1997** [comment]
Should now be fixed with [https://github.com/Globox1997/RpgDifficulty/commit/66b59f12ff5f32d9d10cdafbd6fef510a0ace882](https://github.com/Globox1997/RpgDifficulty/commit/66b59f12ff5f32d9d10cdafbd6fef510a0ace882)
Actually not sure if it fixed it o.o

**Comment by lindenkron** [comment]
Flew around for a good 10 minutes without a crash. I can't state if it's guaranteed fixed or not.

**Comment by Globox1997** [comment]
Reopen if still happening with latest version :)
