### ISSUE TITLE
Boss Health Scaling

### ISSUE THREAD

**Issue by RynShirayuki** [Globox1997/RpgDifficulty#27]
It seems like bosses spawn with their default hp amount out of the changed amount so half the time they are always half dead or so.
![Screenshot_3](https://user-images.githubusercontent.com/39139683/176705143-afe68f78-c8fe-42f0-89f4-20d992f928fa.png)

**Comment by Globox1997** [comment]
Which mod version is this?

**Comment by RynShirayuki** [comment]
rpgdifficulty-1.2.0.jar

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/RpgDifficulty/commit/66b59f12ff5f32d9d10cdafbd6fef510a0ace882](https://github.com/Globox1997/RpgDifficulty/commit/66b59f12ff5f32d9d10cdafbd6fef510a0ace882)
