### ISSUE TITLE
Incompatibility with LootJS, the best JavaScript mod to modify loot tables in fabric.

### ISSUE THREAD

**Issue by TheRobberPanda** [Globox1997/RpgDifficulty#28]
Link to the mod -> https://www.curseforge.com/minecraft/mc-mods/lootjs

[crash-2022-07-07_17.09.04-server.txt](https://github.com/Globox1997/RpgDifficulty/files/9065180/crash-2022-07-07_17.09.04-server.txt)

**Comment by Globox1997** [comment]
Turn off the dropMoreLoot setting in the config.
