### ISSUE TITLE
Crash on Time Scaling 0

### ISSUE THREAD

**Issue by iRewiewer** [Globox1997/RpgDifficulty#3]
Setting `Time Scaling` to `0`, gives `Error: java.lang.ArithmeticException: / by zero` when loading a world. "Ticking world" being the error title.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgDifficulty/commit/1543a1182c9346547701607f3c5bd13a5052d163](https://github.com/Globox1997/RpgDifficulty/commit/1543a1182c9346547701607f3c5bd13a5052d163)
Thanks for reporting :)
