### ISSUE TITLE
[Feature Request] Scale mobs spawned from structure

### ISSUE THREAD

**Issue by elhertz** [Globox1997/RpgDifficulty#31]
I'm using the DungeonsArise mod for fabric and I've realized that mobs spawned by structures don't get scaled by RpgDifficulty

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by elhertz** [comment]
> Which mod version do you use?

[rpgdifficulty-1.2.0.jar](https://www.curseforge.com/minecraft/mc-mods/rpgdifficulty/files/3843929)
Fabric 1.19.2 and the latest version of dungeons arise

here's a video showing that the mob spawned with the dungeons_arise:illager_corsair structure doesn't have a level
https://user-images.githubusercontent.com/13700335/186222688-6b52ce4b-c5ec-4a6b-a31f-816a9e0113ea.mp4

**Comment by Globox1997** [comment]
Mh this should actually already work on 1.19.2....

**Comment by Mr-Syntax** [comment]
im having the same problem, its the mobs from the spawners built in there

like for example an evoker will have the dungeons arise set health but when he summons vex'es they get the correct amount of health

ive found a couple of other mods that dont scale aswell
More Babies
AdventureZ
Incendium

ill write them here once i find more but my pack is pretty extensive but your mod is at the heart of it all
https://www.curseforge.com/minecraft/modpacks/hack-n-craft

**Comment by Mr-Syntax** [comment]
the mobs from dungeons arise which do not work are

Withers
Phantoms
piglins
evokers
pillagers

**Comment by Mr-Syntax** [comment]
actually it seems as he says spawned from structure + entities riding on other entities dont scale

**Comment by Globox1997** [comment]
Definitely fixed in the latest update.
