### ISSUE TITLE
Wiki or more comments in config file

### ISSUE THREAD

**Issue by Coyote21** [Globox1997/RpgDifficulty#33]
Some additional comments explaining all the option in  the config file would be good, or a wiki maybe?
 
In particular, I'm not really clear on what the randomChance and randomFactor option do? Do they just allow for some random variation in mod levels?

**Comment by Globox1997** [comment]
If you want you can edit the readme section and add a wiki part to it :)
the randomChance applies when allowRandomValues is set to true.
 it basically sets the chance for having a random values on the spawning mob

**Comment by Globox1997** [comment]
Added some info to the readme with [https://github.com/Globox1997/RpgDifficulty/commit/7acb644727d5431f2e66bcde8b81f9d064e1ad41](https://github.com/Globox1997/RpgDifficulty/commit/7acb644727d5431f2e66bcde8b81f9d064e1ad41)
