### ISSUE TITLE
What does this actually scale off of?

### ISSUE THREAD

**Issue by KeeveeKoomoo** [Globox1997/RpgDifficulty#34]
I literally have no idea what is causing the mobs to scale, and it would be helpful to have a bit more explanation than simply "time and distance". Does it scale with the LevelZ mod if present? It's not too farfetched an assumption given they are both developed by the same guy. Having played with this mod, I have noticed the mobs becoming stronger, but I don't know what is actually causing the difficulty increase.

**Comment by Globox1997** [comment]
There is an open issue for more info about this mod config :)
It can scale with levelz if levelz compat is enabled (disabled by default), I think only the latest versions.
By default mobs will get stronger over time, I think half an hour about 10% and max by default is double than vanilla.
By distance just means if you go further away from spawn point, each 300 blocks increase the strength by 10% (default)
