### ISSUE TITLE
Crash When Enabling Levelz option

### ISSUE THREAD

**Issue by PixelatedBruh** [Globox1997/RpgDifficulty#35]
Time: 2022-09-10 09:40:47
Description: Exception ticking world

java.lang.NoSuchMethodError: 'net.levelz.stats.PlayerStatsManager net.levelz.access.PlayerStatsManagerAccess.getPlayerStatsManager(net.minecraft.class_1657)'
	at net.rpgdifficulty.api.MobStrengthener.handler$dip000$changeAttributesMixin(MobStrengthener.java:660)
	at net.rpgdifficulty.api.MobStrengthener.changeAttributes(MobStrengthener.java)
	at net.minecraft.class_3218.handler$dic000$spawnEntityMixin(class_3218.java:10215)
	at net.minecraft.class_3218.method_8649(class_3218.java)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5425.method_30771(class_5425.java:11)
	at net.minecraft.class_1948.method_24930(class_1948.java:299)
	at net.minecraft.class_1948.method_8663(class_1948.java:212)
	at net.minecraft.class_1948.method_27821(class_1948.java:200)
	at net.minecraft.class_3215.method_14161(class_3215.java:376)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:319)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.rpgdifficulty.api.MobStrengthener.handler$dip000$changeAttributesMixin(MobStrengthener.java:660)
	at net.rpgdifficulty.api.MobStrengthener.changeAttributes(MobStrengthener.java)
	at net.minecraft.class_3218.handler$dic000$spawnEntityMixin(class_3218.java:10215)
	at net.minecraft.class_3218.method_8649(class_3218.java)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5425.method_30771(class_5425.java:11)
	at net.minecraft.class_1948.method_24930(class_1948.java:299)
	at net.minecraft.class_1948.method_8663(class_1948.java:212)
	at net.minecraft.class_1948.method_27821(class_1948.java:200)
	at net.minecraft.class_3215.method_14161(class_3215.java:376)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:319)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Pixel_Scream'/241, l='ServerLevel[New World]', x=4.50, y=83.00, z=-22.50]]
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,90,-32), Section: (at 0,10,0 in 0,5,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 24 game time, 24 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 64115 (now: false), thunder time: 107603 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 773037408 bytes (737 MiB) / 2004877312 bytes (1912 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75173.76
	Virtual memory used (MB): 18315.80
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 4.55
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.14
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		architectury: Architectury 6.2.43
		auudio: Auudio 1.0.3
		bclib: BCLib 2.1.0
		betteranimationscollection: Better Animations Collection 4.0.1
		bettercombat: Better Combat 1.3.1+1.19
			tinyconfig: TinyConfig 1.0.2
		betterf3: BetterF3 1.3.2
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		clear-skies: Clear Skies 2.0.94
		cloth-config: Cloth Config v8 8.1.77
			cloth-basic-math: cloth-basic-math 0.6.1
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		customstars: Custom Stars 1.1+1.19
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.4
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		eldritch_mobs: EldritchMobs 1.12.6
		emotecraft: Emotecraft 2.2.5
			bendy-lib: Bendy api 2.1.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		fancymenu: FancyMenu 2.12.1
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib3: Geckolib 3.1.18
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		goml: Get Off My Lawn ReServed 1.5.0-pre.5+1.19.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
			playerabilitylib: Pal 1.6.0
			polymer: Polymer (Core) 0.2.10+1.19.1
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19.1
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.3+1.19.1
		hwg: Happiness is a Warm Gun 1.2.6
		illuminations: Illuminations 1.10.8
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.2.8
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.5.0
		lazydfu: LazyDFU 0.1.3
		levelz: LevelZ 1.4.0
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.12.4
		lithium: Lithium 0.8.3
		loadmyresources: Load My Resources 1.0.1
		malilib: MaLiLib 0.13.0
		mca: Minecraft Comes Alive 7.3.21+1.19.2
		medievalweapons: Medieval Weapons 1.4.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		nameplate: Nameplate 1.0.6
		nochatreports: No Chat Reports 1.19.2-v1.11.2
		peacefulsurface: PeacefulSurface 1.19.2-v1-fabric
		player-animator: Player Animator 0.3.5
		puzzleslib: Puzzles Lib 4.3.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		roughlyenoughitems: Roughly Enough Items 9.1.530
			error_notifier: Error Notifier 1.0.9
		rpg-hud: RPG-Hud 3.9.4
		rpgdifficulty: Rpg Difficulty 1.2.1
		satin: Satin 1.9.0
		shouldersurfing: Shoulder Surfing Reloaded 2.2.12
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		spawnermod: Enhanced Mob Spawners 1.2.0
		starlight: Starlight 1.1.1+fabric.ae22326
		tenshilib: TenshiLib 1.19-1.6.10
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		waveycapes: WaveyCapes 1.2.1
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Pixel_Scream'/241, l='ServerLevel[New World]', x=4.50, y=83.00, z=-22.50]]
	Data Packs: vanilla, Fabric Mods, loadmyresources.hiddenpack (incompatible)
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.9-1.19.2

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/RpgDifficulty/commit/c020fb11b85fb5efaa83d1002a6d4c5451e6da6b](https://github.com/Globox1997/RpgDifficulty/commit/c020fb11b85fb5efaa83d1002a6d4c5451e6da6b)
