### ISSUE TITLE
OP bees

### ISSUE THREAD

**Issue by FurryApocalypse** [Globox1997/RpgDifficulty#37]
Hello
So i have problem on my server with RPG difficulty. (fabric latest 1.19.2 version mod)

![image](https://user-images.githubusercontent.com/75454834/196823635-8eac5807-c222-406c-a4bb-88e9ddbceee4.png)

Everytime bee is entering the hive, she comes out with scaled hp up to RPG difficulty. 
Probably the game is counting bee inside as a new entity and when bee is coming out its scaled again over and over.
Is there any possibility to fix this or blacklist some mobs? (currently only bees have such problem)

**Comment by Globox1997** [comment]
Looks like a very overpowered bee xD 
Thanks for reporting, it actually was already a known bug but I fixed it with [https://github.com/Globox1997/RpgDifficulty/commit/fe27e475e77c71d8db028b192fd9c53d63c4d4c2](https://github.com/Globox1997/RpgDifficulty/commit/fe27e475e77c71d8db028b192fd9c53d63c4d4c2)
