### ISSUE TITLE
Crash on Startup (Quilt)

### ISSUE THREAD

**Issue by WrightBruh** [Globox1997/RpgDifficulty#39]
I wasn't sure if this issue was brought up already, but I can't seem to use this mod on Quilt, even with the Quilted Fabric API. I tested this with all other mods disabled, and the crash still occurs. If this is simply an incompatibility with Quilt, that's understandable. But if Quilt support is planned, hopefully this log will help.

https://mclo.gs/9GBsZ5Y

EDIT: I also ran the same test on Fabric (no Quilt), and everything launched working as intended.

EDIT 2: Grammar

**Comment by Globox1997** [comment]
Please read the mod page description, I develop only for fabric out of different reasons, mainly time.

**Comment by NolanHewitt** [comment]
I use quilt and this mod works for me. Something must have changed in the future after this issue.
