### ISSUE TITLE
Boss health problem

### ISSUE THREAD

**Issue by Vantos** [Globox1997/RpgDifficulty#42]
Problem with the lack of health of the boss, elder dragon is working properly, the warden lacks hp, wither 
always ends up charging at 300 hp. Also mod not working properly with bosses from other mods like TwilightForest, sometimes the hp is missing, sometimes the boss is detected as a normal mob. I tried mod on every 1.19.2 version.
![unknown](https://user-images.githubusercontent.com/55363187/199836863-112b37f0-b278-4dfe-9cea-c538e20fe8e0.png)

**Comment by nxp1** [comment]
have the same problem is this fixed already?

**Comment by Globox1997** [comment]
Fixed it with [https://github.com/Globox1997/RpgDifficulty/commit/34de96483f904a0c61d7fdb129d990a8a59691e9](https://github.com/Globox1997/RpgDifficulty/commit/34de96483f904a0c61d7fdb129d990a8a59691e9)
