### ISSUE TITLE
Optifine conflicts

### ISSUE THREAD

**Issue by Mokeysam** [Globox1997/RpgDifficulty#45]
For some reason your RPGDifficulty and Environmentz mods don't not work with optifine. I've gone through all my mods in the folder individually and it is definitely these it doesn't like. Is there any idea why?

**Comment by Globox1997** [comment]
Mh I have no idea and optifine is closed source, so compatibility is not easy.
I recommend to use Iris mod instead of optifine with all performance mods you can get.

**Comment by Globox1997** [comment]
If still persist in latest version, reopen with latest log.
