### ISSUE TITLE
[Feature Request] Difficulty Scaling in Other Dimensions

### ISSUE THREAD

**Issue by Cynicizm** [Globox1997/RpgDifficulty#47]
Enemy mobs don't get stronger in other dimensions no matter how far I travelled (tried it in Nether and End).

I got BetterNether & BetterEnd installed, if that matters.

**Comment by Globox1997** [comment]
do you have default settings enabled?

**Comment by RockZe** [comment]
Also faced with such a problem. Created a datapack and specified the address according to your guide (data\rpgdifficiency\difficulty\YOURFILE.json). But for some reason mobs in other dimensions do not change. 
Maybe I need some additional settings?

I also use BetterNether, BetterEnd and The Twilight Forest.

![image](https://user-images.githubusercontent.com/123874691/215328854-85c833cc-b763-4243-adf3-0503c542281c.png)

**Comment by Mr-Syntax** [comment]
it would be awesome if you could just have a slider multiplier for each dimension so for example i could have a 10x multiplier for the nether and then when you enter the nether its a the same difficulity as in the overworld

**Comment by Globox1997** [comment]
I accidentally used a different id for dimensions than the world registry key. Will be fixed with version 1.3.6
