### ISSUE TITLE
Carryon Mod exponential levelling bug for RPGDifficulty

### ISSUE THREAD

**Issue by Izakde** [Globox1997/RpgDifficulty#49]
Hi,

I am unsure on how to classify this as it in an interaction between two mods, and I have not used github for long, so apologies in advance if this is the wrong area to input this.

When using the Carryon mod for 1.19.2 with RPGDifficulty the mob's level is multiplied by a factor of about 2x. This can lead to some funny scenarios with mobs having 2147483633 levels, but then they become unkillable and immortal without the use of commands or a similarly op mob. This is listed under the Medieval MC github page and I was wondering if it is even solvable or if the interaction is by nature unsolvable.

Here is a link to the Medieval MC github bug with an example video: https://github.com/LunaPixelStudios/Medieval-MC/issues/395

The issue becomes worse as mobs gain higher levels and you want to transport them easily.

Thanks for the response in advance.

**Comment by Globox1997** [comment]
Do you use the latest version?

**Comment by Globox1997** [comment]
This should be fixed with some later version, please reopen if still existent with the latest version.
