### ISSUE TITLE
Suggestion: Make rewards scale with distance (maybe using luck?)

### ISSUE THREAD

**Issue by EmoBubbleGum** [Globox1997/RpgDifficulty#5]
Luck affects a lot of things in minecraft. I was thinking you could make the rewards scale a lot better with the difficulty if you had some kind of scale for luck too. 

Naturally it would be good to have a setting in the config for this. I think this setting could be very easily adjusted to fit any scaling settings, though, i am not sure how hard it would be to implement. Maybe use a custom playerdata variable for tracking player luck/distance?

**Comment by Globox1997** [comment]
Hey EmoBubbleGum,
It is overall a good idea but I think if mobs drop more loot than in the loot table defined, the player would get too much stuff for killing mobs in a short amount of time. Somebody else requested something like this for another mod made by me called LevelZ where the player can skill on luck but even there I don't think this will fit in minecrafts world good

**Comment by Globox1997** [comment]
Added more loot config which depends on the nameplate mod addon with [https://github.com/Globox1997/RpgDifficulty/commit/a5da5b9214f23908a0621f24c281aec58fb0072b](https://github.com/Globox1997/RpgDifficulty/commit/a5da5b9214f23908a0621f24c281aec58fb0072b)
Definitely open for suggestions how to calculate the dropped item count
