### ISSUE TITLE
XP drop don't sale with strength even if I modify some values :(

### ISSUE THREAD

**Issue by ghost** [Globox1997/RpgDifficulty#53]

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by ghost** [comment]
The lasted version, I only have playerex and relicex with your mod Envoyé de mon iPhoneLe 20 mars 2023 à 14:48, Globox_Z ***@***.***> a écrit :﻿
Which mod version do you use?

**Comment by Globox1997** [comment]
Might be fixed in the coming update.

**Comment by ghost** [comment]
Thanks !, I have an amazing idea for you. if you can make more lots drop and exp scaling with her level. I take for exemple a cow : a cow with 100hp drop x10 her loot and x10 her exp (like it’s a stack of 10cow) a zombie with 25hp drop x1.5 her loot and exp because her hp improve x1.5 and same with all mobs, a kind of natural looting improve with more hp. A great interest to go fight strong monsters like real RPG.Envoyé de mon iPhoneLe 20 mars 2023 à 19:37, Globox_Z ***@***.***> a écrit :﻿
Might be fixed in the coming update.

**Comment by Globox1997** [comment]
Reopen if still persistent on latest version.
There is a loot setting ;)
