### ISSUE TITLE
minecells/rpgdifficulty incompatibility

### ISSUE THREAD

**Issue by soupcantrolling** [Globox1997/RpgDifficulty#55]
https://mclo.gs/6PYi4md

1.19.2 fabric,
entered a mine cells portal thing and shortly after the game crashed. the report shows its due to both minecells and the rpg difficulty mod, im guessing it's trying to make one of the rune spawn mobs stronger and it can't find how.

im reporting this on both mods' issue pages

**Comment by Globox1997** [comment]
I see minecells has compat with rpgdifficulty here: [https://github.com/mim1q/MineCells/tree/main/src/main/resources/data/rpgdifficulty/difficulty](https://github.com/mim1q/MineCells/tree/main/src/main/resources/data/rpgdifficulty/difficulty) Have to look into it

**Comment by Globox1997** [comment]
The datapack can get updated but I fixed old datapacks with [https://github.com/Globox1997/RpgDifficulty/commit/1357dbdf10fe00b95220fa8c8106414e22f694ec](https://github.com/Globox1997/RpgDifficulty/commit/1357dbdf10fe00b95220fa8c8106414e22f694ec)
