### ISSUE TITLE
Add ability to configure x and z starting coordinates

### ISSUE THREAD

**Issue by zinerith** [Globox1997/RpgDifficulty#56]
For server compatibility where the spawn has been changed from the default, please add the ability to configure the coordinates from which the factor scaling starts. Currently there doesn't seem to be a way to change it from the default spawn location.

**Comment by Globox1997** [comment]
Check out the datapack system

**Comment by tennomai** [comment]
hey sorry to bother you, any way to do this in the mod right now?
