### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by bigsmokeee12** [Globox1997/RpgDifficulty#58]
When i play singleplayer on my world creatures are lvl 50+ but if i invite my friend by LAN creatures are lvl 1 all the time. How can i change that and have high level of creatures on multiplayer?

**Comment by Globox1997** [comment]
Did you edit the config? If so, show me your edited lines

**Comment by bigsmokeee12** [comment]
Yes i edited it: 
  "increasingDistance": 2000,
  "distanceFactor": 0.75,
  "increasingTime": 30,
  "timeFactor": 0.1,
  "heightDistance": 50,
  "heightFactor": 0.05,
  "maxFactorHealth": 9.55,
  "maxFactorDamage": 7.0,
  "maxFactorProtection": 10.0,
  "maxFactorSpeed": 2.0,
  "allowRandomValues": false,
  "randomChance": 10,
  "randomFactor": 10,
  "extraXp": true,
  "maxXPFactor": 5.0,
  "startingFactor": 1.0,
  "startingDistance": 0,
  "startingTime": 0,
  "startingHeight": 62,
  "positiveHeightIncreasion": true,
  "negativeHeightIncreasion": true,
  "affectBosses": true,
  "excludeDistanceInOtherDimension": true,
  "excludeTimeInOtherDimension": true,
  "excludeHeightInOtherDimension": true,
  "dropMoreLoot": true,
  "moreLootChance": 0.02,
  "maxLootChance": 0.7,
  "chanceForEachItem": 0.5,
  "levelZLevelFactor": 0.0,
  "levelZPlayerRadius": 0.0,
  "hudTesting": false,
  "excludedEntity": [],
  "allowSpecialZombie": true,
  "bigZombieChance": 10,
  "bigZombieSlownessFactor": 0.7,
  "bigZombieBonusLifePoints": 150,
  "bigZombieBonusDamage": 30,
  "bigZombieSize": 1.5,
  "speedZombieChance": 10,
  "speedZombieSpeedFactor": 1.5,
  "speedZombieMalusLifePoints": 10,
  "dynamicBossModification": true,
  "dynamicBossModificator": 0.5,
  "bossMaxFactor": 5.0,
  "bossDistanceFactor": 0.05,
  "bossTimeFactor": 0.0,
  "creeperExplosionFactor": 2.0
}

**Comment by ForionOG** [comment]
i have the same problem on my server and I hadn't changed a thing

**Comment by Globox1997** [comment]
Mh looks good, not sure why it is not working correctly

**Comment by Globox1997** [comment]
Come to my discord.
