### ISSUE TITLE
[Feature Request] Starting distance setting

### ISSUE THREAD

**Issue by elhertz** [Globox1997/RpgDifficulty#6]
Distance from where the mod starts increasing the mob's attributes.

Example: I want to have a 800 block radius with vanilla mobs and then start increasing their stats every 300 blocks.

**Comment by Globox1997** [comment]
Added start settings with [https://github.com/Globox1997/RpgDifficulty/commit/65f53536c108c0b1f906a07a56cbb21a4d0a6ab2](https://github.com/Globox1997/RpgDifficulty/commit/65f53536c108c0b1f906a07a56cbb21a4d0a6ab2)
