### ISSUE TITLE
Can't exclude entities

### ISSUE THREAD

**Issue by Zano1999** [Globox1997/RpgDifficulty#63]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.3.12

### Describe the Issue

Excluding entities in settings doesn't change anything

![image](https://github.com/Globox1997/RpgDifficulty/assets/42555362/fe599cef-48a8-4e64-9461-d244e8b5026b)

![2023-06-21_18 34 59](https://github.com/Globox1997/RpgDifficulty/assets/42555362/43b853cc-361d-4e0f-a393-916710dd9dad)

### latest.log

.

**Comment by Globox1997** [comment]
Do you play on a server? If you play on a server, you have to edit the server config and best is to reload.

**Comment by Zano1999** [comment]
Already solved, I forgot to close the problem, the problem was how I have to insert the entities, the format is "modname.entity", I insert "modname:entity"
