### ISSUE TITLE
v1.19.4?

### ISSUE THREAD

**Issue by bvhfve** [Globox1997/RpgDifficulty#64]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Why is there no 1.19.4 version? v1.13.12 for mc 1.19.3 doesn't seem to work on 1.19.4

**Comment by Globox1997** [comment]
I have no plans to work on 1.19.4
Out of time reasons I only work on the latest version of my mods.

**Comment by bvhfve** [comment]
I can understand that, it's fine though since I moved to 1.20.1 a while ago :)
