### ISSUE TITLE
Enemies not scaling up, stays on level one

### ISSUE THREAD

**Issue by House-Kitty-Mew** [Globox1997/RpgDifficulty#65]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.3.12

### Describe the Issue

no matter the distance or my level, every mob and boss is always level 1

### latest.log

[latest.log](https://github.com/Globox1997/RpgDifficulty/files/12137346/latest.log)

### Do you use any other mods except the required ones?

yes

**Comment by Globox1997** [comment]
RpgDifficulty does not add levels to mobs, just strengthen them.
However if you use a mod like nameplate, this will add a level based on its strength.
Did you change any of the default settings?

**Comment by mathi14811** [comment]
> RpgDifficulty does not add levels to mobs, just strengthen them. However if you use a mod like nameplate, this will add a level based on its strength. Did you change any of the default settings?

I have the same issues, I tried to make the mobs stronger because they were only level 9 at the world border, so I changed "increasingDistance": 300 to 200, but now every mob are at level 21, even the ones at spawn. :S

**Comment by Globox1997** [comment]
So the rpgdifficulty settings have to get set up properly.

**Comment by Lumb3rSamur4i** [comment]
My mobs are always on level 20

**Comment by Globox1997** [comment]
So I recommend to turn off the time settings by turning them to 0, this could lead to confusion.
Otherwise tinker around with the settings. You can also ask me directly at my discord.
