### ISSUE TITLE
[Feature Request] Add level to the mob's name

### ISSUE THREAD

**Issue by elhertz** [Globox1997/RpgDifficulty#7]
![example](https://i.imgur.com/CTe401f.png)

The level could be calculated by the time/distance factor value.
Also it'd be good to have different "Lv.x" colors (like tiers) depending on their level, going from green to red or sth like that.

**Comment by elhertz** [comment]
Smh

**Comment by Globox1997** [comment]
[nameplate-1.0.0.zip](https://github.com/Globox1997/RpgDifficulty/files/7601575/nameplate-1.0.0.zip)
Made a small mod which does this

**Comment by Globox1997** [comment]
cf link: [https://www.curseforge.com/minecraft/mc-mods/nameplate](https://www.curseforge.com/minecraft/mc-mods/nameplate)
