### ISSUE TITLE
I really hope that the author can add the effects of this mod to the Nether and the End

### ISSUE THREAD

**Issue by CMDky2000** [Globox1997/RpgDifficulty#73]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I'm really not going to do packets.I really hope that the author can add the effects of this mod to the Nether and the End.If you agree, then my whole family will really thank you.

**Comment by Globox1997** [comment]
By default, mobs in all dimensions will get strengthened. 
With the datapack system you can specifically change the strength of mobs in each dimension.

**Comment by CMDky2000** [comment]
I already know how to fix it.
